menu:
  Home:
  Archives: archives
  RSS: atom.xml
widgets:
- about
- category
- tagcloud
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid: false
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: false

google_analytics:
rss:

comment_provider: disqus
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

avatar: ./uploads/avatar_tg.jpg

link:
  Note: https://note.xuguorui.xyz
  Github: https://github.com/megrxu
  Telegram: https://t.me/TyteKa